---
title: "Ficha de Información Metropolitana"
author: "Alvaro"
date: "2023-02-27"
output: html_document
runtime: shiny
---
<div style="text-align: justify">  <div/>

La ficha de información metropolitana es una herramienta útil para la planificación territorial en zonas metropolitanas. Esta ficha contiene datos censales en diferentes formatos, como gráficos, tablas y mapas.
El propósito principal de esta ficha es proporcionar datos esenciales para la planificación territorial a nivel de zona metropolitana. Es decir, incluye ciertos conjuntos de datos que recopilan inicialmente el proceso de planificación, los cuales describen las características socioeconómicas y espaciales de la zona.

Sin embargo, es importante destacar que la planificación territorial requiere de un análisis detallado del territorio y de las decisiones específicas que se deben tomar, a partir de las problemáticas específicas y sistémicas, así como las potencialidades del territorio. En este sentido, la ficha proporciona una base sólida de datos, pero es fundamental complementarla con un análisis más detallado y personalizado.

Para crear un menú interactivo en esta serie de fichas, se utiliza la función 'renderUI' del paquete Shiny en conjunto con la función 'uiOutput'. Con renderUI se crea una lista desplegable en la que el usuario pueda seleccionar una variable. Luego, con la ayuda de un controlador en el servidor (observeEvent), se puede responder a la selección del usuario y actualizar la información mostrada en el informe. 

Para la información sociodemográfica se recurrio a los Censos de Población y Vivienda, 2020, en el apartado de Tabulados/Características de las localidades. La base original del Instituto Nacional de Estadística y Geografía (INEGI) se filtró solo para la información a nivel municipal y se eliminaron algunas variables sin relevancia.

En cuanto a la información económica se recurrio a los Censos Económicos publicados por INEGI en el periodo de 1999-2019. Dicha información se proceso a nivel subsector y se estimaron los coeficientes de localización económica (QL), participación relativa (PR),  Hirschmann Herfindahl(HH) y el inverso de Hirschmann Herfindahl(IHH) de cada municipio respecto a su zona metropolitana.

```{r echo=FALSE, message=FALSE, warning=FALSE}
# Importación de la base
library(readxl)
library(shiny)
library(dplyr)
library(tidyverse)
library(openxlsx)
library(shinyWidgets)

# Importar archivos de variables económicas por año

zm99 <- read_excel("..\\Bases de datos\\zm99.xlsx")
zm04 <- read_excel("..\\Bases de datos\\zm04.xlsx")
zm09 <- read_excel("..\\Bases de datos\\zm09.xlsx")
zm14 <- read_excel("..\\Bases de datos\\zm14.xlsx")
zm19 <- read_excel("..\\Bases de datos\\zm19.xlsx")

# Leer archivo de variables sociodemográficas
Base_sociodemo <- read_excel("..\\Bases de datos\\Base _sociodemo.xlsx")

#Se crea la variable cve_geo
Base_sociodemo$cvegeo <- paste(Base_sociodemo$CVE_ENT, Base_sociodemo$MUN, sep = "")

#Colocación de las claves de zona metropolitana

Variables <- select(zm19, cvegeo,  CVE_ZM,  NOM_ZM)
Base_sociodemo <- merge(Base_sociodemo, Variables, by = "cvegeo", all = TRUE)

##Comienza la aplicación

ui <- fluidPage(
  selectInput("zmvm",
              "Selecciona una ZM:",
              unique(Base_sociodemo$NOM_ZM),
              selected = NULL),
  selectInput("variables",
              "Selecciona variables sociodemograficas a mostrar:",
              choices = names(Base_sociodemo),
              multiple = TRUE,
              selected = NULL),
  selectInput("variables2",
            "Selecciona variables economicas a mostrar:",
            choices = c(names(zm99), names(zm04), names(zm09), names(zm14), names(zm19)),
            multiple = TRUE,
            selected = NULL),
  actionButton("ver_municipios", "Ver municipios"),
  tableOutput("informacion"),
  downloadButton("descargar", "Descargar tabla")
)
#Vincula la entrada de usuario con el servidor
server <- function(input, output) {
  
  datos_zm <- reactive({
    subset(Base_sociodemo, NOM_ZM == input$zmvm)
  })
  
  output$informacion <- renderTable({
    datos <- merge(datos_zm(),
                   subset(zm19, NOM_ZM == input$zmvm),
                   by = "cvegeo",
                   all = TRUE)
    tabla <- datos[, c(input$variables, input$variables2), drop = FALSE]
  })
  
  output$descargar <- downloadHandler(
    filename = function() {
      paste("Tabla-", Sys.Date(), ".csv", sep = "")
    },
    content = function(file) {
      datos <- merge(datos_zm(),
                     subset(zm19, NOM_ZM == input$zmvm), 
                     by = "cvegeo",
                     all = TRUE)
      tabla <- datos[,c(input$variables, input$variables2), drop = FALSE]
      write.csv(tabla, file, row.names = FALSE, fileEncoding = "UTF-8")
    }
  )
  
  observeEvent(input$ver_municipios, {
    showModal(modalDialog(
      title = "Municipios de la ZM",
      fluidRow(
        column(width = 12,
               dataTableOutput("tabla_municipios"))
      ),
      footer = modalButton("Cerrar")
    ))
  })
  
  output$tabla_municipios <- renderDataTable({
    datos_zm()
  })
  
}
shinyApp(ui, server)
```